<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>12fc672e-e456-4fab-8eea-5ff18ea20067</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\YHTransporte.Application\YHTransporte.Application.csproj" />
    <ProjectReference Include="..\YHTransporte.Core\YHTransporte.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.11" />
  </ItemGroup>

</Project>
